# Query to generate the adjacency matrix representing the axonal paths of the neuron populations for SCKAN Explorer.

SELECT DISTINCT ?Neuron_IRI ?Neuron_Label ?V1 ?V1_Label ?V2 ?V2_Label
WHERE 
{

    # Note: This query currently works for the NLP curated neuron populations.
    # We will update the query for other populations such as the populations from ApINATOMY models. 
    ?Neuron_IRI rdfs:subClassOf* ilxtr:NeuronSparcNlp.

    ?Neuron_IRI ilxtr:neuronPartialOrder ?PO .
        ?PO (rdf:rest|rdf:first)* ?r1 .
        ?r1 (rdf:rest|rdf:first)* ?r2 .
        ?r1 rdf:first ?V1 .
        ?r2 rdf:first ?V2 .
        ?V1 rdf:type owl:Class .
        ?V2 rdf:type owl:Class .

        FILTER (?mediator = ?r1)  # draw only from the same partial order
        ?mediator rdf:first ?V1 .  # car
        ?mediator rdf:rest+/rdf:first/rdf:first ?V2 .  # caadr

    ?V1 rdfs:label ?V1_Label. ?V2 rdfs:label ?V2_Label.
    ?Neuron_IRI rdfs:label ?Neuron_Label.

    FILTER (?V1 != ?V2).

   # FILTER (CONTAINS(STR(?Neuron_IRI), 'semves/2')).

}
ORDER BY ?Neuron_IRI ?V1 ?V2 
LIMIT 10000