# Query: Major nerves and their synonyms in SCKAN neuron populations
# Version: November 12, 2025. - Fahim Imam

PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX partOf: <http://purl.obolibrary.org/obo/BFO_0000050>
PREFIX ilxtr: <http://uri.interlex.org/tgbugs/uris/readable/>
PREFIX ILX: <http://uri.interlex.org/base/ilx_>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX UBERON: <http://purl.obolibrary.org/obo/UBERON_>
PREFIX NIFRID: <http://uri.neuinfo.org/nif/nifstd/readable/>

SELECT DISTINCT 
# ?Neuron_ID 
?Nerve_IRI ?Nerve_Label ?Nerve_Synonym
{
   ?Neuron_ID rdfs:subClassOf* ?sckan_neuron .
   VALUES ?sckan_neuron { ilxtr:NeuronSparcNlp ilxtr:NeuronApinatSimple }
   
   VALUES ?axon_loaction { ilxtr:hasAxonLocation  ilxtr:hasAxonToSensoryTerminal }.
   # VALUES ?axon_terminal  {ilxtr:hasAxonTerminalLocation  ilxtr:hasAxonSensoryLocation}.
       
   <<?Neuron_ID ?axon_location ?C_IRI>> ilxtr:hasRegion ?Nerve_IRI.
   # <<?Neuron_ID ilxtr:hasSomaLocation ?A_IRI>> ilxtr:hasRegion ?A_ID.
   
   ?Nerve_IRI (rdfs:subClassOf*/rdfs:label) "nerve". # using uberon "nerve" UBERON:0001021

   ?Nerve_IRI rdfs:label ?Nerve_Label.
   OPTIONAL{ ?Nerve_IRI (oboInOwl:hasExactSynonym | oboInOwl:hasRelatedSynonym | NIFRID:synonym) ?Nerve_Synonym. }
}
ORDER BY ?Nerve_Label ?Nerve_IRI
LIMIT 500